[package]
name = "coreum-wasm-sdk"
version = "0.1.2"
edition = "2021"
description = "SDK for WASM coreum messages and queries."
homepage = "https://coreum.com/"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema = "1.2.6"
cosmwasm-std = "1.2.6"
